version: "2.1"

networks:
  thesis:

services:
  api:
    image: api:1.0
    build: .
    networks:
      - thesis
    ports:
      - 4000:4000
    extra_hosts:
      - "orderer.thesis.com:34.67.248.87"
      - "orderer2.thesis.com:34.67.248.87"
      - "orderer3.thesis.com:34.67.248.87"
      - "peer0.thayson.thesis.com:34.67.248.87"
      - "peer1.thayson.thesis.com:34.67.248.87"
      - "peer0.cohuong.thesis.com:35.224.10.90"
      - "peer1.cohuong.thesis.com:35.224.10.90"
      - "ca.thayson.thesis.com:34.67.248.87"
