version: "2.1"

networks:
  thesis:

services:
  api:
    image: api:1.0
    build: .
    networks:
      - thesis
    ports:
      - 4000:4000
    extra_hosts:
      - "orderer.thesis.com:34.136.122.109"
      - "orderer2.thesis.com:34.136.122.109"
      - "orderer3.thesis.com:34.136.122.109"
      - "peer0.thayson.thesis.com:34.136.122.109"
      - "peer1.thayson.thesis.com:34.136.122.109"
      - "ca.thayson.thesis.com:34.136.122.109"
